

// import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900" />

                <link href="/assets/css/nucleo-icon.css" rel="stylesheet" />
                <link href="/assets/css/nucleo-svg.css" rel="stylesheet" />

                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />

                <link id="pagestyle" href="/assets/css/material-dashboard.min2167.css?v=3.2.0" rel="stylesheet" />

            </head>
            <body className="g-sidenav-show  bg-gray-100">
                {children}
            </body>
        </html>
    );
}
