"use client"

import Sidebar from "@/_component/Sidebar";
import '../(main)/globals.css'

import Footer from "@/_component/Footer";
import Header from "@/_component/Header";
import { useState } from "react";
import 'react-datepicker/dist/react-datepicker.css';


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [sidebar, setSidebar] = useState(false)
  const toggleSidebar = () => {
    setSidebar((prevState) => !prevState);
  };

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900" />

        <link href="/assets/css/nucleo-icons.css" rel="stylesheet" />

        <link href="/assets/css/nucleo-svg.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"/>

        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />

        <link href="/assets/css/material-dashboard.min2167.css?v=3.2.0" rel="stylesheet" />

        <link href="/assets/css/coustom.css" rel="stylesheet" />

      </head>
      <body className={`${sidebar ? "g-sidenav-show dark-version bg-gray-600 g-sidenav-pinned" : "g-sidenav-show dark-version bg-gray-600"}`}>
        <Sidebar />
        <main className="main-content position-relative max-height-vh-100 h-100 border-radius-lg">
          <Header toggleSidebar={toggleSidebar} />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
